### ISSUE TITLE
MCPE , DragonetProxy?

### ISSUE THREAD

**Issue by NycuRO** [DaMatrix/PorkProxy#1]
Can you create one Proxy like Dragonet? (Like as Mineplex) ? :)

**Comment by DaMatrix** [comment]
This is just gonna be for PC. I want to be able to test bots and be able to see what they do from the same account, but from different machines. Proxying PC and PE is a) beyond my abilities and b) not really possible.

**Comment by NycuRO** [comment]
@DaMatrix And Mineplex how work ?:P

**Comment by DaMatrix** [comment]
Mineplex PE is totally PE servers, you can't play with PC and PE users on Mineplex.

**Comment by NycuRO** [comment]
@DaMatrix Uses one Proxy like that: Proxy -> Bungee -> MCPE now work on pc

**Comment by DaMatrix** [comment]
No, it doesn't. You can't play with PC players on Mineplex PE.

**Comment by NycuRO** [comment]
Ohhhh -_-
